### ISSUE TITLE
Seeli command allows creating flags with duplicate "shorthand" attributes

### ISSUE THREAD

**Issue by jmoses** [esatterwhite/node-seeli#113]
I have no other words although maybe I will write a test case on a fork.

**Comment by esatterwhite** [comment]
Example would be fine to clarify what happened

**Comment by jmoses** [comment]
```
  -a, --app                             <string>                      The app to apply to
  -a, --add, --no-add                   <boolean> [false]             
```

Had the same `shorthand` value on multiple flags to one command.  Not sure which one "won", but I would expect my CLI library to throw in this case, rather than pretend it was a-ok lol
