### ISSUE TITLE
Should flags be passed to the `onContent` function of a Command?

### ISSUE THREAD

**Issue by evanlucas** [esatterwhite/node-seeli#41]
I really like how the `Command#onContent` option separates the return value from the output. A lot of tools allow an `--output` option. It would be nice to be able to know the cli flags in the onContent function.

**Comment by esatterwhite** [comment]
I'm pretty sure the calling context for that is the command

```javascript
onContent.call(this)
```

you should be able to access `this.argv` or `this.parsed`, no?

**Comment by evanlucas** [comment]
oof yea, good call
